const NODES=[

{id:"中际旭创",code:"300308",group:"光模块",type:"a",rating:"S",py:"zjxc",products:["800G光模块","1.6T光模块","硅光模块"]},
{id:"新易盛",code:"300502",group:"光模块",type:"a",rating:"A",py:"xys",products:["800G光模块","1.6T光模块","400G光模块"]},
{id:"天孚通信",code:"300394",group:"光器件",type:"a",rating:"A",py:"tftx",products:["光无源器件(连接器/分路器)","TFLN调制器"]},
{id:"光迅科技",code:"002281",group:"光模块",type:"a",rating:"A",py:"gxkj",products:["800G光模块","光有源器件(放大器/调制器)","光无源器件(连接器/分路器)"]},
{id:"华工科技",code:"000988",group:"光模块",type:"a",rating:"A",py:"hgkj",products:["800G光模块","光有源器件(放大器/调制器)"]},
{id:"铭普光磁",code:"002902",group:"光模块",type:"a",rating:"B",py:"mpgc",products:["400G光模块","光有源器件(放大器/调制器)"]},
{id:"博创科技",code:"300548",group:"光器件",type:"a",rating:"B",py:"bckj",products:["光无源器件(连接器/分路器)","AWG芯片"]},
{id:"腾景科技",code:"688195",group:"光器件",type:"a",rating:"B",py:"tjkj",products:["精密光学元件","AWG芯片"]},
{id:"太辰光",code:"300570",group:"光器件",type:"a",rating:"B",py:"tcg",products:["光无源器件(连接器/分路器)"]},
{id:"德科立",code:"688205",group:"光器件",type:"a",rating:"B",py:"dkl",products:["光有源器件(放大器/调制器)"]},
{id:"剑桥科技",code:"603083",group:"光模块",type:"a",rating:"C",py:"jqkj",products:["800G光模块"]},
{id:"联特科技",code:"301205",group:"光模块",type:"a",rating:"C",py:"ltkj",products:["800G光模块","1.6T光模块"]},
{id:"长飞光纤",code:"601869",group:"光纤光缆",type:"a",rating:"B",py:"cfgx",products:["特种光纤","通信光缆"]},
{id:"亨通光电",code:"600487",group:"光纤光缆",type:"a",rating:"B",py:"htgd",products:["特种光纤","通信光缆"]},
{id:"烽火通信",code:"600498",group:"通信设备",type:"a",rating:"B",py:"fhtx",products:["通信光缆","5G通信模组"]},
{id:"源杰科技",code:"688498",group:"光芯片",type:"a",rating:"A",py:"yjkj",products:["EML激光器芯片","DFB激光器芯片"]},
{id:"长光华芯",code:"688048",group:"光芯片",type:"a",rating:"B",py:"cghx",products:["EML激光器芯片","VCSEL芯片"]},
{id:"仕佳光子",code:"688313",group:"光芯片",type:"a",rating:"B",py:"sjgz",products:["AWG芯片","DFB激光器芯片"]},
{id:"沪硅产业",code:"688126",group:"半导体材料",type:"a",rating:"A",py:"hgcy",products:["300mm硅片"]},
{id:"中芯国际",code:"688981",group:"晶圆代工",type:"a",rating:"S",py:"zxgj",products:["先进制程晶圆代工(14nm以下)","成熟制程晶圆代工"]},
{id:"华虹公司",code:"688347",group:"晶圆代工",type:"a",rating:"A",py:"hhgs",products:["成熟制程晶圆代工"]},{id:"晶合集成",code:"688249",group:"晶圆代工",type:"a",rating:"B",py:"jhjc",products:["成熟制程晶圆代工"]},{id:"甬矽电子",code:"688362",group:"先进封装",type:"a",rating:"A",py:"yxdz",products:["先进封装(FC-BGA/SiP)","晶圆级封装"]},
{id:"北方华创",code:"002371",group:"半导体设备",type:"a",rating:"A",py:"bfhc",products:["刻蚀设备","薄膜沉积设备(PVD/CVD)","清洗设备"]},
{id:"中微公司",code:"688012",group:"半导体设备",type:"a",rating:"A",py:"zwgs",products:["刻蚀设备","薄膜沉积设备(CVD)"]},
{id:"盛美上海",code:"688082",group:"半导体设备",type:"a",rating:"A",py:"smsh",products:["清洗设备","半导体电镀设备"]},
{id:"拓荆科技",code:"688072",group:"半导体设备",type:"a",rating:"A",py:"tjkj",products:["薄膜沉积设备(PVD/CVD)"]},
{id:"芯源微",code:"688037",group:"半导体设备",type:"a",rating:"B",py:"xyw",products:["涂胶显影设备"]},
{id:"华大九天",code:"301269",group:"半导体设备",type:"a",rating:"B",py:"hdjt",products:["EDA工具"]},
{id:"华峰测控",code:"688200",group:"半导体设备",type:"a",rating:"B",py:"hfck",products:["检测量测设备"]},
{id:"华海清科",code:"688120",group:"半导体设备",type:"a",rating:"A",py:"hhqk",products:["CMP设备"]},
{id:"长川科技",code:"300604",group:"半导体设备",type:"a",rating:"B",py:"cckj",products:["检测量测设备"]},
{id:"南大光电",code:"300346",group:"半导体材料",type:"a",rating:"A",py:"ndgd",products:["电子特气","光刻胶","前驱体"]},
{id:"彤程新材",code:"603650",group:"半导体材料",type:"a",rating:"B",py:"tcxc",products:["光刻胶","电子级树脂"]},
{id:"华特气体",code:"688268",group:"半导体材料",type:"a",rating:"A",py:"htqt",products:["电子特气"]},
{id:"中船特气",code:"688146",group:"半导体材料",type:"a",rating:"A",py:"zctq",products:["电子级三氟化氮"]},
{id:"金宏气体",code:"688106",group:"半导体材料",type:"a",rating:"B",py:"jhqt",products:["电子特气"]},
{id:"江丰电子",code:"300666",group:"半导体材料",type:"a",rating:"A",py:"jfdz",products:["溅射靶材"]},
{id:"安集科技",code:"688019",group:"半导体材料",type:"a",rating:"A",py:"ajkj",products:["CMP抛光液","光刻胶"]},
{id:"有研新材",code:"600206",group:"半导体材料",type:"a",rating:"B",py:"yxc",products:["溅射靶材","电子特气"]},{id:"有研硅",code:"688432",group:"半导体材料",type:"a",rating:"A",py:"yg",products:["300mm硅片"]},
{id:"晶瑞电材",code:"300655",group:"半导体材料",type:"a",rating:"B",py:"jrdc",products:["光刻胶","电子级硫酸","电子级氢氟酸"]},
{id:"上海新阳",code:"300236",group:"半导体材料",type:"a",rating:"B",py:"shxy",products:["电子级硫酸","光刻胶"]},
{id:"雅克科技",code:"002409",group:"半导体材料",type:"a",rating:"A",py:"ykkj",products:["前驱体","电子特气","电子级硅微粉"]},
{id:"立昂微",code:"605358",group:"半导体材料",type:"a",rating:"A",py:"law",products:["300mm硅片"]},
{id:"鼎龙股份",code:"300054",group:"半导体材料",type:"a",rating:"A",py:"dlgf",products:["CMP抛光液","光刻胶"]},
{id:"天岳先进",code:"688234",group:"半导体材料",type:"a",rating:"B",py:"tyj",products:["碳化硅衬底"]},
{id:"联瑞新材",code:"688300",group:"半导体材料",type:"a",rating:"B",py:"lrxc",products:["电子级硅微粉"]},
{id:"石英股份",code:"603688",group:"半导体材料",type:"a",rating:"B",py:"sygf",products:["半导体用石英制品(坩埚/管/舟)"]},
{id:"长电科技",code:"600584",group:"先进封装",type:"a",rating:"A",py:"cdkj",products:["先进封装(FC-BGA/SiP)","晶圆级封装"]},
{id:"通富微电",code:"002156",group:"先进封装",type:"a",rating:"A",py:"tfwd",products:["先进封装(FC-BGA/SiP)"]},
{id:"华天科技",code:"002185",group:"先进封装",type:"a",rating:"B",py:"htkj",products:["先进封装(FC-BGA/SiP)","晶圆级封装"]},
{id:"格科微",code:"688728",group:"芯片设计",type:"a",rating:"B",py:"gkw",products:["CIS图像传感器"]},
{id:"翱捷科技",code:"688220",group:"芯片设计",type:"a",rating:"C",py:"ajkj",products:["SoC芯片","AIoT芯片"]},
{id:"龙芯中科",code:"688047",group:"芯片设计",type:"a",rating:"B",py:"lxzk",products:["CPU"]},
{id:"思瑞浦",code:"688536",group:"芯片设计",type:"a",rating:"B",py:"srp",products:["模拟芯片"]},
{id:"圣邦股份",code:"300661",group:"芯片设计",type:"a",rating:"B",py:"sbgf",products:["模拟芯片"]},
{id:"澜起科技",code:"688008",group:"芯片设计",type:"a",rating:"A",py:"lqkj",products:["DDR内存接口芯片"]},
{id:"韦尔股份",code:"603501",group:"芯片设计",type:"a",rating:"A",py:"wegf",products:["CIS图像传感器","触控芯片"]},
{id:"兆易创新",code:"603986",group:"芯片设计",type:"a",rating:"B",py:"zycx",products:["存储控制芯片","MCU"]},
{id:"卓胜微",code:"300782",group:"芯片设计",type:"a",rating:"B",py:"zsw",products:["射频前端芯片"]},
{id:"海光信息",code:"688041",group:"芯片设计",type:"a",rating:"A",py:"hgxx",products:["CPU"]},
{id:"寒武纪",code:"688256",group:"芯片设计",type:"a",rating:"A",py:"hwj",products:["AI训练芯片"]},
{id:"汇顶科技",code:"603160",group:"芯片设计",type:"a",rating:"B",py:"hdkj",products:["触控芯片"]},
{id:"瑞芯微",code:"603893",group:"芯片设计",type:"a",rating:"B",py:"rxw",products:["SoC芯片","AIoT芯片"]},
{id:"恒玄科技",code:"688608",group:"芯片设计",type:"a",rating:"B",py:"hxkj",products:["AIoT芯片"]},
{id:"全志科技",code:"300458",group:"芯片设计",type:"a",rating:"B",py:"qzkj",products:["SoC芯片"]},
{id:"紫光国微",code:"002049",group:"芯片设计",type:"a",rating:"B",py:"zggw",products:["FPGA","SoC芯片"]},
{id:"江波龙",code:"301308",group:"存储模组",type:"a",rating:"B",py:"jbl",products:["企业级SSD","消费级存储模组"]},
{id:"北京君正",code:"300223",group:"芯片设计",type:"a",rating:"B",py:"bjjz",products:["CPU","存储控制芯片"]},
{id:"富瀚微",code:"300613",group:"芯片设计",type:"a",rating:"C",py:"fhw",products:["SoC芯片"]},
{id:"沪电股份",code:"002463",group:"PCB",type:"a",rating:"A",py:"hdgf",products:["高速多层PCB"]},
{id:"深南电路",code:"002916",group:"PCB",type:"a",rating:"A",py:"sndl",products:["高速多层PCB","IC载板"]},
{id:"鹏鼎控股",code:"002938",group:"PCB",type:"a",rating:"A",py:"pdkg",products:["高速多层PCB","FPC柔性板","HDI板"]},
{id:"胜宏科技",code:"300476",group:"PCB",type:"a",rating:"A",py:"shkj",products:["高速多层PCB","HDI板"]},
{id:"东山精密",code:"002384",group:"PCB",type:"a",rating:"A",py:"dsjm",products:["FPC柔性板","高速多层PCB"]},
{id:"生益科技",code:"600183",group:"CCL覆铜板",type:"a",rating:"A",py:"sykj",products:["CCL覆铜板","高速多层PCB"]},{id:"华正新材",code:"603186",group:"CCL覆铜板",type:"a",rating:"C",py:"hzxc",products:["CCL覆铜板"]},{id:"东材科技",code:"601208",group:"电子树脂",type:"a",rating:"A",py:"dckj",products:["电子级树脂"]},{id:"菲利华",code:"300395",group:"石英材料",type:"a",rating:"A",py:"flh",products:["半导体用石英制品(坩埚/管/舟)"]},{id:"宏和科技",code:"603256",group:"电子布",type:"a",rating:"B",py:"hhkj",products:["电子级玻璃纤维布"]},{id:"国际复材",code:"301526",group:"电子布",type:"a",rating:"B",py:"gjfc",products:["电子级玻璃纤维布"]},{id:"中国巨石",code:"600176",group:"玻纤",type:"a",rating:"B",py:"zgjs",products:["电子级玻璃纤维"]},
{id:"芯碁微装",code:"688630",group:"半导体设备",type:"a",rating:"B",py:"xqwz",products:["直写光刻设备"]},
{id:"兴森科技",code:"002436",group:"IC载板",type:"a",rating:"B",py:"xskj",products:["IC载板","ABF载板"]},
{id:"铂科新材",code:"300811",group:"被动元件",type:"a",rating:"A",py:"bkxc",products:["磁粉芯"]},
{id:"三环集团",code:"300408",group:"被动元件",type:"a",rating:"B",py:"shjt",products:["MLCC"]},
{id:"顺络电子",code:"002138",group:"被动元件",type:"a",rating:"B",py:"sldz",products:["电感"]},
{id:"风华高科",code:"000636",group:"被动元件",type:"a",rating:"B",py:"fhgk",products:["MLCC","电阻"]},
{id:"英维克",code:"002837",group:"散热",type:"a",rating:"A",py:"ywk",products:["数据中心液冷系统"]},
{id:"沃尔核材",code:"002130",group:"散热",type:"a",rating:"C",py:"wec",products:["热缩材料"]},
{id:"传音控股",code:"688036",group:"终端品牌",type:"a",rating:"B",py:"cykg",products:["手机终端"]},
{id:"浪潮信息",code:"000977",group:"服务器",type:"a",rating:"A",py:"lxx",products:["AI服务器","通用服务器"]},
{id:"中科曙光",code:"603019",group:"服务器",type:"a",rating:"B",py:"zksg",products:["AI服务器","通用服务器"]},
{id:"纳思达",code:"002180",group:"终端",type:"a",rating:"C",py:"nsd",products:["SoC芯片"]},
{id:"移远通信",code:"603236",group:"模组",type:"a",rating:"B",py:"yytx",products:["5G通信模组","蜂窝物联网模组"]},
{id:"广和通",code:"300638",group:"模组",type:"a",rating:"B",py:"ght",products:["5G通信模组","蜂窝物联网模组"]},
{id:"中兴通讯",code:"000063",group:"通信设备",type:"a",rating:"B",py:"zxtx",products:["5G通信模组","通信光缆"]},{id:"紫光股份",code:"000938",group:"网络设备",type:"a",rating:"A",py:"zggf",products:["AI服务器"]},{id:"盛科通信",code:"688702",group:"交换芯片",type:"a",rating:"A",py:"sktx",products:["数据中心交换芯片"]},
{id:"海康威视",code:"002415",group:"安防",type:"a",rating:"B",py:"hkws",products:["AI视觉SoC","安防AI"]},
{id:"比亚迪",code:"002594",group:"终端",type:"a",rating:"A",py:"byd",products:["新能源车"]},
{id:"宁德时代",code:"300750",group:"电池",type:"a",rating:"S",py:"ndsd",products:["动力电池","储能电池"]},
{id:"阳光电源",code:"300274",group:"新能源",type:"a",rating:"B",py:"ygdy",products:["逆变器"]},
{id:"锦浪科技",code:"300763",group:"新能源",type:"a",rating:"B",py:"jlkj",products:["逆变器"]},
{id:"格力电器",code:"000651",group:"终端",type:"a",rating:"C",py:"gldq",products:["MCU"]},
{id:"美的集团",code:"000333",group:"终端",type:"a",rating:"C",py:"mjt",products:["MCU"]},
{id:"京东方",code:"000725",group:"面板",type:"a",rating:"B",py:"jdf",products:["LCD面板","柔性OLED"]},
{id:"工业富联",code:"601138",group:"代工组装",type:"a",rating:"A",py:"gyfl",products:["AI服务器代工","消费电子代工"]},
{id:"立讯精密",code:"002475",group:"代工组装",type:"a",rating:"A",py:"lxjm",products:["消费电子代工"]},
{id:"歌尔股份",code:"002241",group:"代工组装",type:"a",rating:"B",py:"gegf",products:["消费电子代工","MEMS传感器代工"]},
{id:"云南锗业",code:"002428",group:"关键矿产",type:"a",rating:"B",py:"ynzy",products:["锗"]},
{id:"北方稀土",code:"600111",group:"关键矿产",type:"a",rating:"A",py:"bfxt",products:["稀土氧化物"]},
{id:"洛阳钼业",code:"603993",group:"关键矿产",type:"a",rating:"B",py:"ymy",products:["钴","钼","铜"]},
{id:"锡业股份",code:"000960",group:"关键矿产",type:"a",rating:"B",py:"xygf",products:["锡"]},
{id:"厦门钨业",code:"600549",group:"关键矿产",type:"a",rating:"B",py:"xmwy",products:["钨"]},{id:"中钨高新",code:"000657",group:"工具耗材",type:"a",rating:"C",py:"zwgx",products:["数控刀具","PCB微钻"]},{id:"大族数控",code:"301200",group:"PCB设备",type:"a",rating:"C",py:"dzsk",products:["PCB钻孔设备"]},
{id:"铜陵有色",code:"000630",group:"关键矿产",type:"a",rating:"C",py:"tls",products:["铜"]},
{id:"华友钴业",code:"603799",group:"关键矿产",type:"a",rating:"A",py:"hgy",products:["钴"]},
{id:"赣锋锂业",code:"002460",group:"关键矿产",type:"a",rating:"A",py:"gfly",products:["锂化合物"]},
{id:"天齐锂业",code:"002466",group:"关键矿产",type:"a",rating:"B",py:"tqly",products:["锂化合物"]},
{id:"驰宏锌锗",code:"600497",group:"关键矿产",type:"a",rating:"B",py:"chxz",products:["锗","锌"]},
{id:"包钢股份",code:"600010",group:"关键矿产",type:"a",rating:"B",py:"bggf",products:["稀土氧化物"]},
{id:"中科三环",code:"000970",group:"磁材",type:"a",rating:"B",py:"zksh",products:["钕铁硼永磁体"]},
{id:"金力永磁",code:"300748",group:"磁材",type:"a",rating:"B",py:"jlc",products:["钕铁硼永磁体"]},
{id:"富创精密",code:"688409",group:"零部件",type:"a",rating:"A",py:"fcjm",products:["半导体设备精密零部件(腔体/管路)"]},
{id:"国瓷材料",code:"300285",group:"材料",type:"a",rating:"B",py:"gccl",products:["MLCC","电子级硅微粉"]},
{id:"麦格米特",code:"002851",group:"电源",type:"a",rating:"A",py:"mgt",products:["AI服务器电源"]},
{id:"鼎通科技",code:"688668",group:"连接器",type:"a",rating:"C",py:"dtkj",products:["高速背板连接器"]},
{id:"光库科技",code:"300620",group:"光器件",type:"a",rating:"A",py:"gkkj",products:["TFLN调制器","铌酸锂晶圆"]},
{id:"赛微电子",code:"300456",group:"MEMS",type:"a",rating:"B",py:"swdz",products:["MEMS传感器代工"]},
{id:"高德红外",code:"002414",group:"红外",type:"a",rating:"B",py:"gdhw",products:["红外探测器/热像仪"]},
{id:"兴发集团",code:"600141",group:"化工",type:"a",rating:"C",py:"xfjt",products:["电子级磷酸","电子级氢氟酸"]},
{id:"多氟多",code:"002407",group:"氟化工",type:"a",rating:"B",py:"dfd",products:["电子级氢氟酸","锂化合物"]},
{id:"嘉元科技",code:"688388",group:"铜箔",type:"a",rating:"B",py:"jykj",products:["超薄电子铜箔"]},
{id:"诺德股份",code:"600110",group:"铜箔",type:"a",rating:"B",py:"ndgf",products:["超薄电子铜箔"]},{id:"铜冠铜箔",code:"301217",group:"铜箔",type:"a",rating:"C",py:"tgtb",products:["超薄电子铜箔"]},
{id:"当升科技",code:"300073",group:"正极材料",type:"a",rating:"B",py:"dskj",products:["三元正极材料"]},
{id:"容百科技",code:"688005",group:"正极材料",type:"a",rating:"B",py:"rbkj",products:["高镍正极材料"]},
{id:"中伟股份",code:"300919",group:"前驱体",type:"a",rating:"B",py:"zwgf",products:["三元前驱体"]},
{id:"拓普集团",code:"601689",group:"汽车零部件",type:"a",rating:"A",py:"tpjt",products:["轻量化铝合金零部件"]},
{id:"三花智控",code:"002050",group:"热管理",type:"a",rating:"A",py:"shzk",products:["车用热管理系统"]},
{id:"旭升集团",code:"603305",group:"汽车零部件",type:"a",rating:"C",py:"xsjt",products:["轻量化铝合金零部件"]},
{id:"均胜电子",code:"600699",group:"汽车电子",type:"a",rating:"B",py:"jsdz",products:["汽车电子(HMI/安全)"]},
{id:"德赛西威",code:"002920",group:"汽车电子",type:"a",rating:"B",py:"dsxw",products:["汽车电子(座舱域控)"]},
{id:"亿纬锂能",code:"300014",group:"电池",type:"a",rating:"B",py:"ywln",products:["动力电池","储能电池"]},
{id:"国轩高科",code:"002074",group:"电池",type:"a",rating:"B",py:"ggk",products:["动力电池"]},
{id:"威迈斯",code:"688612",group:"电源",type:"a",rating:"C",py:"wms",products:["车载电源"]},
{id:"中航光电",code:"002179",group:"连接器",type:"a",rating:"B",py:"zhgd",products:["高速背板连接器","基站连接器"]},
{id:"泰和新材",code:"002254",group:"新材料",type:"a",rating:"C",py:"thxc",products:["芳纶"]},
{id:"中国稀土",code:"000831",group:"关键矿产",type:"a",rating:"B",py:"zgxt",products:["稀土氧化物"]},
{id:"华峰铝业",code:"601702",group:"铝材",type:"a",rating:"C",py:"hfly",products:["铝合金热管理材料"]},
{id:"天通股份",code:"600330",group:"半导体材料",type:"a",rating:"A",py:"ttgf",products:["铌酸锂晶圆","精密光学元件"]},
{id:"Soitec",code:"SOI",group:"半导体材料",type:"o",rating:"A",py:"stc",products:["SOI晶圆"]},
{id:"三井金属",code:"5713",group:"铜箔",type:"o",rating:"A",py:"sjs",products:["超薄电子铜箔"]},
{id:"台积电",code:"TSM",group:"晶圆代工",type:"o",rating:"S",py:"tjd",products:["先进制程晶圆代工(14nm以下)","成熟制程晶圆代工"]},
{id:"三星电子",group:"IDM",type:"o",rating:"A",py:"sxdz",products:["存储芯片","CIS图像传感器"]},
{id:"SK海力士",group:"存储",type:"o",rating:"A",py:"hls",products:["存储芯片"]},
{id:"美光",code:"MU",group:"存储",type:"o",rating:"A",py:"mg",products:["存储芯片"]},
{id:"英伟达",code:"NVDA",group:"AI芯片",type:"o",rating:"S",py:"ywd",products:["AI训练GPU"]},
{id:"AMD",code:"AMD",group:"CPU",type:"o",py:"amd",products:["CPU","AI训练GPU"]},
{id:"英特尔",code:"INTC",group:"CPU",type:"o",rating:"A",py:"yte",products:["CPU"]},
{id:"高通",code:"QCOM",group:"通信芯片",type:"o",rating:"A",py:"gt",products:["SoC芯片"]},
{id:"博通",code:"AVGO",group:"通信芯片",type:"o",rating:"A",py:"bt",products:["数据中心交换芯片"]},
{id:"苹果",code:"AAPL",group:"终端品牌",type:"o",rating:"S",py:"pg",products:["手机终端"]},
{id:"特斯拉",code:"TSLA",group:"终端品牌",type:"o",rating:"S",py:"tsl",products:["新能源车","人形机器人"]},
{id:"谷歌",code:"GOOGL",group:"云厂",type:"o",rating:"S",py:"gg",products:["云服务"]},
{id:"微软",code:"MSFT",group:"云厂",type:"o",rating:"A",py:"wr",products:["云服务"]},
{id:"亚马逊",code:"AMZN",group:"云厂",type:"o",rating:"A",py:"ymx",products:["云服务"]},
{id:"Meta",code:"META",group:"云厂",type:"o",py:"meta",products:["Llama模型","社交平台"]},
{id:"ASML",code:"ASML",group:"设备",type:"o",rating:"S",py:"asml",products:["光刻机整机"]},
{id:"东京电子",code:"8035",group:"设备",type:"o",rating:"A",py:"djdz",products:["刻蚀设备","薄膜沉积设备(PVD/CVD)"]},
{id:"应用材料",code:"AMAT",group:"设备",type:"o",rating:"A",py:"yycl",products:["薄膜沉积设备(PVD/CVD)","CMP设备"]},
{id:"泛林",code:"LRCX",group:"设备",type:"o",rating:"A",py:"fl",products:["刻蚀设备","薄膜沉积设备(CVD)"]},
{id:"科磊",code:"KLAC",group:"设备",type:"o",rating:"A",py:"kl",products:["检测量测设备"]},
{id:"格罗方德",code:"GFS",group:"晶圆代工",type:"o",py:"gfd",products:["成熟制程晶圆代工"]},
{id:"联华电子",code:"UMC",group:"晶圆代工",type:"o",py:"lhdz",products:["成熟制程晶圆代工"]},
{id:"村田",code:"6981",group:"被动元件",type:"o",py:"ct",products:["MLCC"]},
{id:"AXT",code:"AXTI",group:"衬底",type:"o",rating:"A",py:"axt",products:["砷化镓衬底","磷化铟衬底"]},
{id:"三菱电机",code:"MIELY",group:"芯片",type:"o",py:"sldj",products:["功率半导体"]},
{id:"Lumentum",code:"LITE",group:"光芯片",type:"o",py:"lum",products:["EML激光器芯片","光无源器件(连接器/分路器)"]},
{id:"Coherent",code:"COHR",group:"光芯片",type:"o",py:"coh",products:["EML激光器芯片","探测器芯片"]},
{id:"华为",group:"终端/通信",type:"n",rating:"S",py:"hw",products:["SoC芯片","AI服务器","5G通信模组"]},
{id:"长江存储",group:"存储制造",type:"n",rating:"A",py:"cj",products:["存储芯片"]},
{id:"长鑫存储",code:"688825",group:"存储制造",type:"a",rating:"A",py:"cx",products:["存储芯片"]},
{id:"OPPO",group:"终端品牌",type:"n",py:"oppo",products:["手机终端"]},
{id:"vivo",group:"终端品牌",type:"n",py:"vivo",products:["手机终端"]},
{id:"小米",group:"终端品牌",type:"n",py:"xm",products:["手机终端","IoT"]},{id:"小鹏",code:"XPEV",group:"终端品牌",type:"o",py:"xp",products:["新能源车"]},{id:"大众",code:"VWAGY",group:"终端品牌",type:"o",py:"dz",products:["新能源车"]},
{id:"上海微电子",group:"半导体设备",type:"n",rating:"A",py:"smee",products:["光刻机整机"]},
{id:"华卓精科",group:"半导体设备",type:"n",rating:"A",py:"hzjk",products:["光刻机工件台"]},
{id:"茂莱光学",code:"688502",group:"精密光学",type:"a",rating:"A",py:"mlgx",products:["精密光学元件"]},
{id:"珂玛科技",code:"301611",group:"半导体设备",type:"a",rating:"B",py:"kmkj",products:["半导体设备精密零部件(腔体/管路)"]},
{id:"鼎泰高科",code:"301377",group:"工具耗材",type:"a",rating:"A",py:"dtgk",products:["PCB微钻","数控刀具"]},
// === 机器人链 2026-07-28 ===
{id:"汇川技术",code:"300124",group:"伺服驱动",type:"a",rating:"A",py:"hcjs",products:["伺服驱动器","无框力矩电机"]},
{id:"绿的谐波",code:"688017",group:"减速器",type:"a",rating:"A",py:"ldxb",products:["谐波减速器"]},
{id:"双环传动",code:"002472",group:"减速器",type:"a",rating:"A",py:"shcd",products:["RV减速器","谐波减速器"]},
{id:"柯力传感",code:"603662",group:"传感器",type:"a",rating:"B",py:"klcg",products:["六维力传感器"]},
{id:"埃斯顿",code:"002747",group:"机器人本体",type:"a",rating:"B",py:"asd",products:["工业机器人","伺服驱动器"]},
{id:"鸣志电器",code:"603728",group:"伺服驱动",type:"a",rating:"B",py:"mzdq",products:["步进系统","无框力矩电机"]},
// === 机器人链 第二批 2026-07-28 ===
{id:"雷赛智能",code:"002979",group:"伺服驱动",type:"a",rating:"A",py:"lszn",products:["伺服驱动器","步进系统"]},
{id:"兆威机电",code:"003021",group:"机器人本体",type:"a",rating:"A",py:"zwjd",products:["灵巧手","关节模组"]},
{id:"双林股份",code:"300100",group:"执行器",type:"a",rating:"B",py:"slgf",products:["行星滚柱丝杠","关节模组"]},
{id:"步科股份",code:"688160",group:"伺服驱动",type:"a",rating:"B",py:"bkgf",products:["伺服驱动器"]},
{id:"奥比中光",code:"688322",group:"传感器",type:"a",rating:"B",py:"abzg",products:["3D视觉传感器"]},
{id:"五洲新春",code:"603667",group:"执行器",type:"a",rating:"B",py:"wzxc",products:["行星滚柱丝杠"]},
// === 机器人链 下游整机 2026-07-28 ===
{id:"宇树科技",group:"机器人本体",type:"n",py:"yskj",products:["人形机器人"]},
{id:"智元机器人",group:"机器人本体",type:"n",py:"zyjqr",products:["人形机器人"]},
// === 机器人链 第三批 2026-07-28 ===
{id:"中大力德",code:"002896",group:"减速器",type:"a",rating:"A",py:"zddd",products:["谐波减速器","行星减速器"]},
{id:"长盛轴承",code:"300718",group:"执行器",type:"a",rating:"B",py:"cszc",products:["自润滑轴承"]},
{id:"禾川科技",code:"688320",group:"伺服驱动",type:"a",rating:"B",py:"hckj",products:["伺服驱动器"]},
{id:"蓝思科技",code:"300433",group:"机器人本体",type:"a",rating:"B",py:"lskj",products:["人形机器人","消费电子代工"]},
{id:"富临精工",code:"300432",group:"执行器",type:"a",rating:"B",py:"fljg",products:["行星滚柱丝杠","关节模组"]},
{id:"汉威科技",code:"300007",group:"传感器",type:"a",rating:"B",py:"hwkj",products:["触觉传感器"]},
{id:"博众精工",code:"688097",group:"机器人本体",type:"a",rating:"B",py:"bzjg",products:["工业机器人"]},
// === 光刻机链 补充 2026-07-28 ===
{id:"福晶科技",code:"002222",group:"精密光学",type:"a",rating:"A",py:"fjkj",products:["非线性光学晶体","精密光学元件"]},
{id:"波长光电",code:"301421",group:"精密光学",type:"a",rating:"B",py:"bcgd",products:["精密光学镜头"]},
{id:"至纯科技",code:"603690",group:"半导体设备",type:"a",rating:"A",py:"zckj",products:["清洗设备","半导体设备精密零部件(腔体/管路)"]},
{id:"宇量晟",group:"半导体设备",type:"n",rating:"A",py:"yls",products:["光刻机零部件"]},
// === 光刻机链 补充 2026-07-28 ===
{id:"海立股份",code:"600619",group:"半导体设备",type:"a",rating:"B",py:"hlgf",products:["半导体设备精密零部件(腔体/管路)"]},
{id:"新莱应材",code:"300260",group:"半导体设备",type:"a",rating:"B",py:"xlyc",products:["半导体设备精密零部件(腔体/管路)"]},
{id:"高澜股份",code:"300499",group:"散热",type:"a",rating:"B",py:"glgf",products:["数据中心液冷系统"]},
{id:"蔚蓝锂芯",code:"002245",group:"电源",type:"a",rating:"B",py:"wlxx",products:["动力电池"]},
{id:"南亚新材",code:"688519",group:"CCL覆铜板",type:"a",rating:"B",py:"nyxc",products:["CCL覆铜板"]},

];

// ===== 供应链条边 v3.1 大幅扩充 =====
const EDGES=[
{source:"源杰科技",target:"中际旭创",type:"L1",method:"L1_equity",confidence:0.99},{source:"源杰科技",target:"新易盛",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"行业报道/讯石光通讯/钛媒体"},{source:"源杰科技",target:"光迅科技",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"产业链分析/光通信行业报告"},{source:"源杰科技",target:"华工科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"间接证据/产业链推断"},{source:"源杰科技",target:"铭普光磁",type:"L1",method:"L1_direct",confidence:0.95},{source:"源杰科技",target:"博创科技",type:"L1",method:"L1_direct",confidence:0.95},{source:"中际旭创",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"2025年报MD&A：与谷歌、微软、英伟达等北美头部云厂商建立长期稳定合作"},{source:"中际旭创",target:"谷歌",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"光模块→谷歌TPU数据中心，英伟达/谷歌为核心客户"},{source:"中际旭创",target:"微软",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"光模块→微软Azure数据中心"},{source:"中际旭创",target:"亚马逊",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"光模块→AWS数据中心"},{source:"新易盛",target:"Meta",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"光模块→Meta数据中心，行业报道"},{source:"新易盛",target:"英伟达",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"光模块→英伟达GPU集群互联，行业共识非年报命名"},{source:"天孚通信",target:"中际旭创",type:"L1",method:"L2_news",confidence:0.70,sourceDoc:"光器件→光模块，行业共识，天孚为中际核心光引擎供应商"},{source:"天孚通信",target:"英伟达",type:"L1",method:"L2_news",confidence:0.80,sourceDoc:"英伟达GTC 2025认可天孚为核心供应商，FAU/光引擎供应商"},{source:"光迅科技",target:"华为",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"光模块→华为基站/数据中心，同属中国信科集团"},{source:"华工科技",target:"华为",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"光模块→华为，子公司云岭光电自研光芯片"},{source:"腾景科技",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"精密光学元件→光模块厂商"},{source:"太辰光",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"光纤连接器/器件→光模块厂商"},{source:"太辰光",target:"新易盛",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"光纤连接器→光模块厂商"},{source:"德科立",target:"谷歌",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"光放大器→谷歌数据中心"},{source:"光库科技",target:"谷歌",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"光器件→谷歌数据中心"},{source:"赛微电子",target:"谷歌",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"MEMS传感器→谷歌"},{source:"剑桥科技",target:"英伟达",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"LPO光模块经Arista交换机→英伟达GPU集群，英伟达供应商百强名单"},{source:"联特科技",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"光模块→中兴通讯设备"},{source:"长光华芯",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"25G DFB光芯片→中际H200光模块，新闻报道"},{source:"仕佳光子",target:"长飞光纤",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"PLC分路器/AWG→光纤光缆厂商"},{source:"仕佳光子",target:"亨通光电",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"PLC分路器/AWG→光纤光缆厂商"},
{source:"沪硅产业",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"大硅片核心供应商，年报披露导入中芯国际"},{source:"沪硅产业",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"大硅片供应商"},{source:"沪硅产业",target:"台积电",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"大硅片供应商，已进入台积电供应链"},{source:"沪硅产业",target:"格罗方德",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"大硅片供应商"},{source:"沪硅产业",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"大硅片供应商"},{source:"立昂微",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"2024年报：12英寸硅片已进入中芯国际等客户"},{source:"立昂微",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"12英寸硅片供应商"},{source:"天岳先进",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"SiC衬底，国产替代早期，未进入前五大"},{source:"南大光电",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"电子特气/前驱体，年报：成功导入国内领先芯片制造企业"},{source:"南大光电",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"电子特气供应商"},{source:"南大光电",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"电子特气供应商"},{source:"彤程新材",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"光刻胶国产化核心供应商"},{source:"彤程新材",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"光刻胶供应商"},{source:"彤程新材",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"光刻胶供应商"},{source:"华特气体",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"电子特气核心供应商，年报确认"},{source:"华特气体",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"电子特气供应商"},{source:"华特气体",target:"台积电",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"电子特气供应商，已进台积电"},{source:"华特气体",target:"长江存储",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"电子特气供应商"},{source:"中船特气",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3/WF6核心供应商，年报确认中芯国际为客户"},{source:"中船特气",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3/WF6供应商，年报确认长江存储为客户"},{source:"中船特气",target:"台积电",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3已进入台积电3nm制程，2nm验证中，年报披露"},{source:"中船特气",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3/WF6供应商，年报确认华虹集团为客户"},{source:"中船特气",target:"SK海力士",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3供应商，年报确认SK海力士为客户"},{source:"中船特气",target:"长鑫存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"WF6→DRAM制造，年报确认长鑫为客户"},{source:"金宏气体",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"大宗气体供应商"},{source:"金宏气体",target:"华虹公司",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"大宗气体供应商"},{source:"晶瑞电材",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"光刻胶/高纯试剂，验证中"},{source:"晶瑞电材",target:"华虹公司",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"光刻胶验证中"},{source:"上海新阳",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"清洗液/电镀液核心供应商"},{source:"上海新阳",target:"台积电",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"电镀液供应商"},{source:"江丰电子",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"溅射靶材核心供应商，年报确认"},{source:"江丰电子",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"靶材供应商"},{source:"江丰电子",target:"台积电",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"靶材供应商，已进台积电"},{source:"江丰电子",target:"长江存储",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"溅射靶材供应商"},{source:"安集科技",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"CMP抛光液核心供应商"},{source:"安集科技",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CMP抛光液供应商"},{source:"安集科技",target:"台积电",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CMP抛光液，已进台积电"},{source:"有研新材",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"半导体溅射靶材→晶圆PVD/CVD工序"},{source:"有研新材",target:"华虹公司",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"靶材→晶圆制造"},{source:"鼎龙股份",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CMP抛光垫龙头，年报确认导入主流晶圆厂"},{source:"鼎龙股份",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CMP抛光垫供应商"},{source:"雅克科技",target:"SK海力士",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"前驱体/特气，年报：获海力士批量订单"},{source:"雅克科技",target:"三星电子",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"前驱体供应商"},{source:"雅克科技",target:"长鑫存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"前驱体供应商"},{source:"联瑞新材",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"硅微粉填料，间接供应"},{source:"石英股份",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"石英件，非直接物料供应"},
{source:"北方华创",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"刻蚀/薄膜/炉管/清洗设备国产龙头，年报确认"},{source:"北方华创",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"设备供应商"},{source:"北方华创",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"设备供应商"},{source:"北方华创",target:"长鑫存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"设备供应商"},{source:"中微公司",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"等离子刻蚀设备龙头"},{source:"中微公司",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"3D NAND刻蚀设备核心供应商"},{source:"盛美上海",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"清洗设备核心供应商"},{source:"盛美上海",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"清洗设备供应商"},{source:"拓荆科技",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CVD/PVD设备核心供应商"},{source:"拓荆科技",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"PECVD/ALD供应商"},{source:"芯源微",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"涂胶显影设备，国产替代早期"},{source:"芯源微",target:"长鑫存储",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"涂胶显影设备"},{source:"华海清科",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"CMP设备唯一国产供应商，年报确认"},{source:"华海清科",target:"长鑫存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CMP设备供应商"},{source:"华峰测控",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"半导体测试机，份额较小"},{source:"长川科技",target:"长电科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"测试分选机→封测厂"},{source:"长川科技",target:"通富微电",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"测试机→封测厂"},{source:"华大九天",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"EDA工具授权，非物料供应关系"},{source:"富创精密",target:"北方华创",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"半导体设备精密零部件平台供应商，年报确认供货北方华创"},
{source:"富创精密",target:"中微公司",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"半导体设备精密零部件平台供应商，年报确认供货中微公司"},
{source:"富创精密",target:"拓荆科技",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"半导体设备精密零部件平台供应商，年报确认供货拓荆科技"},
{source:"富创精密",target:"ASML",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"第三方产业报道提及进入ASML供应链（精密结构件），年报仅概括表述'国内外龙头客户验证'未直接点名"},
{source:"富创精密",target:"东京电子",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"研报点名'为东京电子等国内外企业提供服务'，非年报直接确认"},{source:"ASML",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"光刻机独家供应商，全球格局"},{source:"ASML",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"光刻机供应商"},{source:"东京电子",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"涂胶显影/刻蚀设备，全球格局"},{source:"东京电子",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"刻蚀设备供应商"},{source:"应用材料",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"全球设备龙头，PVD/CVD/刻蚀"},{source:"泛林",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"刻蚀/沉积设备，全球格局"},{source:"科磊",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"检测量测设备龙头"},{source:"科磊",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"检测设备供应商"},
{source:"中芯国际",target:"长电科技",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"晶圆→封测，国内行业基本盘"},{source:"中芯国际",target:"通富微电",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"晶圆→封测"},{source:"中芯国际",target:"华天科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"晶圆→封测"},{source:"华虹公司",target:"长电科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"特色工艺晶圆→封测"},{source:"格科微",target:"传音控股",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CIS芯片→手机，招股书确认"},{source:"格科微",target:"OPPO",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"CIS芯片客户"},{source:"格科微",target:"华为",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"CIS芯片客户"},{source:"格科微",target:"vivo",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"CIS芯片客户"},{source:"格科微",target:"小米",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"CIS芯片客户"},{source:"韦尔股份",target:"小米",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CIS芯片→手机品牌"},{source:"韦尔股份",target:"华为",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CIS芯片客户"},{source:"韦尔股份",target:"比亚迪",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"车载CIS→比亚迪"},{source:"韦尔股份",target:"海康威视",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"CIS芯片→安防"},{source:"卓胜微",target:"小米",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"射频前端→手机品牌"},{source:"卓胜微",target:"OPPO",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"射频前端客户"},{source:"汇顶科技",target:"OPPO",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"指纹/触控芯片→手机"},{source:"汇顶科技",target:"vivo",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"指纹芯片客户"},{source:"格罗方德",target:"瑞芯微",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"SoC芯片→晶圆代工"},{source:"中芯国际",target:"瑞芯微",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"SoC芯片→晶圆代工"},{source:"台积电",target:"恒玄科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"智能音频SoC→晶圆代工"},{source:"台积电",target:"全志科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"SoC芯片→晶圆代工"},{source:"台积电",target:"紫光国微",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"特种FPGA→晶圆代工"},{source:"富瀚微",target:"海康威视",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"ISP芯片→安防龙头"},{source:"翱捷科技",target:"移远通信",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"蜂窝基带芯片→模组厂"},{source:"翱捷科技",target:"广和通",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"基带芯片→模组厂"},{source:"翱捷科技",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"基带芯片→设备商"},{source:"台积电",target:"翱捷科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"芯片设计→晶圆代工"},{source:"联华电子",target:"翱捷科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"芯片设计→晶圆代工"},{source:"高通",target:"移远通信",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"通信模组→芯片供应商"},{source:"通富微电",target:"龙芯中科",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CPU封装测试，战略合作"},{source:"龙芯中科",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"国产CPU→服务器"},{source:"龙芯中科",target:"纳思达",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"国产CPU→打印设备"},{source:"海光信息",target:"中科曙光",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"x86 CPU→服务器，信创核心链"},{source:"寒武纪",target:"中科曙光",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"AI训练芯片→服务器"},{source:"海光信息",target:"浪潮信息",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"国产CPU→服务器"},{source:"澜起科技",target:"三星电子",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"DDR5内存接口芯片，年报确认供应全球存储厂"},{source:"澜起科技",target:"SK海力士",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"DDR5接口芯片"},{source:"澜起科技",target:"美光",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"DDR5接口芯片"},{source:"澜起科技",target:"英特尔",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"DDR5接口芯片"},{source:"中芯国际",target:"江波龙",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"存储模组→晶圆制造，间接"},
{source:"芯碁微装",target:"鹏鼎控股",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"直写光刻设备→PCB制造商，行业共识"},{source:"芯碁微装",target:"深南电路",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"直写光刻设备→PCB制造商，行业共识"},{source:"芯碁微装",target:"华天科技",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"直写光刻→先进封装，设备商通用客户"},{source:"芯碁微装",target:"长电科技",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"直写光刻→先进封装，设备商通用客户"},{source:"芯碁微装",target:"胜宏科技",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"直写光刻设备→PCB制造商，行业共识"},{source:"生益科技",target:"沪电股份",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"CCL全球#2→AI服务器PCB龙头，研报确认合作开发低损耗覆铜板"},{source:"生益科技",target:"胜宏科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"CCL→PCB，国内最大CCL+一线PCB厂"},{source:"生益科技",target:"深南电路",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"CCL→PCB/IC载板，行业共识"},{source:"生益科技",target:"鹏鼎控股",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"CCL→FPC龙头"},{source:"沪电股份",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"花旗研报确认AI-PCB主力供应商，年报+互动易点名英伟达GPU平台板卡出货"},{source:"沪电股份",target:"华为",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"通信/网络设备PCB供应商，华为核心供应链"},{source:"胜宏科技",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"英伟达PCB核心供应商，花旗/券商多次确认+交易所互动平台记录"},{source:"深南电路",target:"华为",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"华为系PCB/IC载板核心供应商"},{source:"鹏鼎控股",target:"苹果",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"苹果FPC核心供应商，全球最大PCB厂商"},{source:"东山精密",target:"苹果",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"苹果FPC/精密制造供应商"},{source:"东山精密",target:"特斯拉",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"特斯拉精密结构件供应商"},{source:"兴森科技",target:"华为",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"IC载板→华为海思封装"},
{source:"铂科新材",target:"阳光电源",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"金属磁粉芯→光伏逆变器，年报释义段列出阳光电源为客户"},{source:"铂科新材",target:"华为",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"芯片电感/磁粉芯→华为，年报释义段列出"},{source:"铂科新材",target:"比亚迪",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"金属磁粉芯→新能源汽车，年报释义段列出"},{source:"铂科新材",target:"中兴通讯",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"磁粉芯→通信电源"},{source:"铂科新材",target:"格力电器",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"磁粉芯→变频空调"},{source:"铂科新材",target:"美的集团",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"磁粉芯→变频家电"},{source:"铂科新材",target:"英伟达",type:"L2",method:"L2_news",confidence:0.85,sourceDoc:"芯片电感进入英伟达供应链，年报提及GPU芯片电源应用"},{source:"三环集团",target:"华为",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"MLCC/陶瓷封装基座→华为基站/手机"},{source:"三环集团",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"MLCC→新能源汽车电子"},{source:"顺络电子",target:"小米",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"电感/滤波器→小米手机/IoT"},{source:"顺络电子",target:"华为",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"电感/滤波器→华为基站/手机"},{source:"风华高科",target:"华为",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"MLCC/电阻→华为"},{source:"风华高科",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"MLCC→新能源汽车"},{source:"国瓷材料",target:"村田",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"MLCC介质粉体→全球MLCC龙头，互动易确认海外客户"},{source:"国瓷材料",target:"风华高科",type:"L2",method:"L1_direct",confidence:0.85,sourceDoc:"MLCC粉体核心供应商，互动易2022-01-28确认风华是客户"},{source:"国瓷材料",target:"三环集团",type:"L2",method:"L1_direct",confidence:0.85,sourceDoc:"MLCC粉体核心供应商，互动易2022-01-28确认三环是客户"},{source:"国瓷材料",target:"顺络电子",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"MLCC粉体→电感龙头，行业共识"},{source:"思瑞浦",target:"华为",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"信号链模拟芯片→华为基站/服务器"},{source:"思瑞浦",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"模拟芯片→中兴通讯设备"},{source:"圣邦股份",target:"华为",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"电源管理/信号链→华为全系"},{source:"圣邦股份",target:"小米",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"模拟芯片→小米手机/IoT"},{source:"圣邦股份",target:"海康威视",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"模拟芯片→安防设备"},{source:"圣邦股份",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"模拟芯片→通信设备"},
{source:"英维克",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"液冷龙头，进入英伟达GB200/300 NVL72供应商RVL名单，研报+公司公告确认"},{source:"麦格米特",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"AI服务器电源供应商，字节/阿里/腾讯/百度电源订单在供，研报+互动易确认"},{source:"鼎通科技",target:"英伟达",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"高速连接器→经代工厂/服务器OEM→英伟达GPU平台，间接供应"},{source:"工业富联",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"AI服务器组装核心伙伴，年报确认营收同比增3倍+"},{source:"立讯精密",target:"苹果",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"最大组装厂之一，年报确认大客户"},{source:"歌尔股份",target:"苹果",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"声学/VR组装供应商"},{source:"京东方",target:"苹果",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"OLED屏幕供应商"},{source:"拓普集团",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"底盘/内饰供应商，年报确认"},{source:"三花智控",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"热管理核心供应商"},{source:"旭升集团",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"铝合金精密压铸件供应商"},{source:"均胜电子",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"安全系统/智能座舱供应商"},{source:"宁德时代",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"动力电池核心供应商"},{source:"比亚迪",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"竞合关系-刀片电池供货协议"},{source:"中科三环",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"钕铁硼永磁→特斯拉电机"},{source:"东山精密",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"结构件/FPC供应商"},{source:"东山精密",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"PCB(Multek)+光模块(索尔思)双线供AI链，多份研报cross-check"},{source:"铜冠铜箔",target:"东山精密",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"PCB铜箔→FPC/PCB制造商"},{source:"生益科技",target:"东山精密",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"CCL→PCB/FPC制造商"},{source:"宏和科技",target:"东山精密",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"电子布→PCB，间接供应"},{source:"高通",target:"小米",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"骁龙芯片→手机，全球格局"},{source:"高通",target:"OPPO",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"骁龙芯片供应商"},{source:"高通",target:"vivo",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"骁龙芯片供应商"},{source:"博通",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"DSP/EML光芯片→光模块，行业共识非年报点名"},{source:"深南电路",target:"华为",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB/IC载板核心供应商，年报确认"},{source:"沃尔核材",target:"华为",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"线缆/高分子材料供应商"},{source:"长电科技",target:"华为",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"先进封装供应商，年报确认"},{source:"兆易创新",target:"华为",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"NOR Flash/MCU→华为全系产品"},{source:"长电科技",target:"高通",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"封测供应商"},{source:"通富微电",target:"AMD",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"AMD封测核心供应商，年报确认"},{source:"英特尔",target:"浪潮信息",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"x86 CPU→服务器，全球格局"},{source:"AMD",target:"中科曙光",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"EPYC CPU→服务器"},
{source:"云南锗业",target:"长飞光纤",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"锗→光纤掺杂，锗材料主要供应商"},{source:"云南锗业",target:"亨通光电",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"锗→光纤掺杂"},{source:"云南锗业",target:"高德红外",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"锗→红外光学镜头"},{source:"云南锗业",target:"源杰科技",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"锗→半导体衬底，间接关系"},{source:"北方稀土",target:"中科三环",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"稀土→烧结钕铁硼永磁，国内最大稀土供应商"},{source:"北方稀土",target:"金力永磁",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"稀土→钕铁硼永磁，行业核心供应关系"},{source:"包钢股份",target:"北方稀土",type:"L2",method:"L1_equity",confidence:0.99,sourceDoc:"包钢控股北方稀土+稀土精矿独家供应，关联交易公开披露"},{source:"厦门钨业",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.35,sourceDoc:"钨→硬质合金→半导体加工工具，多级传递"},{source:"铜陵有色",target:"嘉元科技",type:"L2",method:"L2_news",confidence:0.40,sourceDoc:"电解铜→铜箔，铜箔上游原料供应"},{source:"铜陵有色",target:"诺德股份",type:"L2",method:"L2_news",confidence:0.40,sourceDoc:"电解铜→铜箔，上游原料"},{source:"铜陵有色",target:"生益科技",type:"L2",method:"L2_news",confidence:0.35,sourceDoc:"铜→铜箔→CCL，多级传递"},{source:"嘉元科技",target:"沪电股份",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"铜箔→PCB，锂电铜箔转PCB铜箔逻辑合理"},{source:"嘉元科技",target:"胜宏科技",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"铜箔→PCB"},{source:"嘉元科技",target:"宁德时代",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"锂电铜箔核心供应商，宁德时代长期合作"},{source:"诺德股份",target:"沪电股份",type:"L2",method:"L2_news",confidence:0.40,sourceDoc:"铜箔→PCB"},{source:"锡业股份",target:"鹏鼎控股",type:"L2",method:"L2_news",confidence:0.35,sourceDoc:"锡→焊料→PCB，多级传递"},{source:"锡业股份",target:"东山精密",type:"L2",method:"L2_news",confidence:0.35,sourceDoc:"锡→焊料→PCB/FPC"},{source:"赣锋锂业",target:"宁德时代",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"氢氧化锂→宁德时代，多年长协供货，赣锋年报提及全球一线电池客户"},{source:"天齐锂业",target:"宁德时代",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"锂精矿/锂盐→宁德时代，全球锂业龙头"},{source:"华友钴业",target:"中伟股份",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"钴/镍→三元前驱体，前驱体龙头上游"},{source:"华友钴业",target:"当升科技",type:"L1",method:"L1_direct",confidence:0.70,sourceDoc:"钴/镍→正极材料"},{source:"中伟股份",target:"宁德时代",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"三元前驱体→宁德时代，核心供应商"},{source:"中伟股份",target:"容百科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"前驱体→正极材料，容百自产部分前驱体"},{source:"当升科技",target:"宁德时代",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"正极材料→宁德时代，长期供应商"},{source:"容百科技",target:"宁德时代",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"高镍正极→宁德时代，核心供应商"},{source:"中国稀土",target:"北方稀土",type:"L2",method:"L2_news",confidence:0.35,sourceDoc:"同为稀土集团，非直接供应关系，行业并列"},{source:"兴发集团",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.35,sourceDoc:"电子级磷酸→晶圆制造，多级供应链"},{source:"多氟多",target:"三星电子",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"电子级氢氟酸→半导体，已进三星供应链"},{source:"多氟多",target:"SK海力士",type:"L2",method:"L2_news",confidence:0.40,sourceDoc:"电子级氢氟酸→半导体"},{source:"泰和新材",target:"长飞光纤",type:"L2",method:"L2_news",confidence:0.40,sourceDoc:"芳纶→光缆增强材料"},{source:"亿纬锂能",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"锂电池→车企，小鹏/宝马等为主要客户"},{source:"阳光电源",target:"宁德时代",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"储能系统→电芯采购，阳光储能业务需外购电芯"},{source:"锦浪科技",target:"阳光电源",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"逆变器同行竞争，非直接供应"},{source:"新易盛",target:"亚马逊",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"光模块→AWS数据中心，新易盛海外云厂客户"},{source:"德赛西威",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"智能座舱/自动驾驶域控→比亚迪，Tier1供应商"},{source:"华峰铝业",target:"宁德时代",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"铝材→电池热管理系统"},{source:"国际复材",target:"生益科技",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"电子布→CCL覆铜板，生益为国内CCL龙头"},{source:"国际复材",target:"华正新材",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"电子布→CCL覆铜板"},{source:"国际复材",target:"南亚新材",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"电子布→CCL覆铜板"},{source:"威迈斯",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"车载电源→比亚迪，新能源汽车电源供应商"},{source:"中航光电",target:"华为",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"连接器→华为基站/服务器/汽车"},
{source:"Lumentum",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"EML激光器芯片→光模块，行业格局非年报披露"},{source:"Coherent",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"VCSEL/EML光芯片→光模块"},{source:"三菱电机",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"EML光芯片→光模块"},{source:"腾景科技",target:"天孚通信",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"精密光学元件→光模块上游"},{source:"光库科技",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"TFLN调制器→光模块，产业报道+研报，1.6T已批量出货"},
{source:"天通股份",target:"中际旭创",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"三年长协年供30万片铌酸锂晶圆，年报可验证"},
{source:"光库科技",target:"天通股份",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"铌酸锂晶圆→TFLN调制器，天通为光库核心晶圆供应商"},
{source:"光库科技",target:"新易盛",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"TFLN调制器→光模块，1.6T/3.2T验证中，产业报道"},{source:"洛阳钼业",target:"宁德时代",type:"L1",method:"L1_equity",confidence:0.95,sourceDoc:"2021年CATL入股KFM铜钴矿25%，钴金属长期供应协议"},{source:"亨通光电",target:"华为",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"光纤光缆→通信设备龙头"},{source:"北京君正",target:"小米",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"存储芯片/SoC→手机品牌"},{source:"北京君正",target:"OPPO",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"存储芯片/SoC→手机品牌"},{source:"北京君正",target:"海康威视",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"安防存储芯片/SoC→安防龙头"},{source:"京东方",target:"华为",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"LCD/OLED面板→华为旗舰机，全球LCD第一出货量"},{source:"京东方",target:"小米",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"面板→小米手机/电视"},{source:"京东方",target:"OPPO",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"OLED面板→OPPO旗舰机"},{source:"京东方",target:"vivo",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"面板→vivo手机"},{source:"赣锋锂业",target:"亿纬锂能",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"氢氧化锂→动力/储能电池厂"},{source:"天齐锂业",target:"亿纬锂能",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"锂盐→电池制造商"},{source:"华友钴业",target:"亿纬锂能",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"钴/镍→三元电池正极"},{source:"中际旭创",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"5G前传/中传/回传光模块→电信设备商"},{source:"新易盛",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"光模块→电信设备商"},{source:"江波龙",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"eSSD→AI服务器"},{source:"沪电股份",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"AI服务器/HPC高速PCB供应"},{source:"深南电路",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"PCB/IC载板→通信设备商"},{source:"中科三环",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"钕铁硼永磁→电动车驱动电机，全球最大磁材+中国最大车企"},{source:"金力永磁",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"钕铁硼永磁→电动车驱动电机"},{source:"亿纬锂能",target:"小鹏",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"2025互动易：自2020年与小鹏合作迄今累计超15万台，P7+全系搭载亿纬电池"},{source:"国轩高科",target:"大众",type:"L1",method:"L1_equity",confidence:0.95,sourceDoc:"大众持股26%为第一大股东，战略合作开发标准电芯"},{source:"洛阳钼业",target:"华友钴业",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"DRC铜钴矿→钴冶炼，印尼华越镍钴项目合作"},{source:"厦门钨业",target:"中科三环",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"稀土原料→永磁材料，产业链上下游但非直接1对1供应"},{source:"厦门钨业",target:"金力永磁",type:"L2",method:"L2_news",confidence:0.45,sourceDoc:"稀土原料→永磁材料"},{source:"沪电股份",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.85,sourceDoc:"通信PCB→中兴通讯，申万/华安研报cross-check确认三大通信客户之一"},{source:"深南电路",target:"英伟达",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"IC载板→AI芯片封装，内资最大封装基板供应商"},{source:"宏和科技",target:"生益科技",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"电子布→覆铜板，年报点名生益科技为客户"},{source:"中国巨石",target:"生益科技",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"电子玻纤→CCL，全球玻纤#1市占23%"},{source:"诺德股份",target:"生益科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"电子电路铜箔→覆铜板"},{source:"诺德股份",target:"鹏鼎控股",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"电子电路铜箔→FPC龙头"},{source:"嘉元科技",target:"生益科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"铜箔→覆铜板，主供锂电兼供CCL"},{source:"铜冠铜箔",target:"生益科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"PCB铜箔→CCL，年报释义列生益科技为关键客户"},{source:"菲利华",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"半导体石英耗材→晶圆蚀刻/扩散/氧化工序"},{source:"菲利华",target:"华虹公司",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"石英玻璃→晶圆制造"},{source:"菲利华",target:"长江存储",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"石英耗材→3D NAND制造"},{source:"东材科技",target:"生益科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"高速电子树脂→CCL，互动平台：通过生益科技供英伟达/华为/苹果"},{source:"华正新材",target:"沪电股份",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"CCL→PCB，生益科技竞对"},{source:"华正新材",target:"深南电路",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"CCL→PCB/IC载板"},{source:"铜冠铜箔",target:"华正新材",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"HVLP铜箔→CCL，华正长期锁价大客户"},{source:"铜冠铜箔",target:"鹏鼎控股",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"FPC用压延铜箔→FPC龙头，物理路径跳过CCL直接贴合"},{source:"宏和科技",target:"华正新材",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"高端超薄电子布→CCL"},{source:"中国巨石",target:"华正新材",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"电子玻纤布→CCL"},{source:"东材科技",target:"华正新材",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"改性低损耗树脂→CCL"},{source:"工业富联",target:"苹果",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"iPhone核心代工商+通信设备组装"},{source:"工业富联",target:"谷歌",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"AI服务器→谷歌云，年报确认云服务商营收增3倍+"},{source:"工业富联",target:"微软",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"AI服务器→Azure"},{source:"工业富联",target:"亚马逊",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"AI服务器→AWS"},{source:"鹏鼎控股",target:"立讯精密",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"FPC/PCB→苹果组装代工商"},{source:"有研硅",target:"中芯国际",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"12英寸硅片→晶圆代工"},{source:"有研硅",target:"华虹公司",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"硅片→特色工艺代工"},{source:"有研硅",target:"长江存储",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"硅片→3D NAND制造"},{source:"沪硅产业",target:"晶合集成",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"大硅片→DDIC/CIS代工"},{source:"有研硅",target:"晶合集成",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"12英寸硅片→晶圆代工"},{source:"晶合集成",target:"韦尔股份",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CIS晶圆代工→韦尔CIS芯片"},{source:"中芯国际",target:"甬矽电子",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"晶圆→先进封装SiP/FC/Bumping"},{source:"华虹公司",target:"甬矽电子",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"特色工艺晶圆→先进封装"},{source:"甬矽电子",target:"恒玄科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"先进封测→智能音频SoC，招股书/年报确认"},{source:"甬矽电子",target:"韦尔股份",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"先进封测→CIS芯片"},{source:"甬矽电子",target:"北京君正",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"先进封测→存储/SoC芯片"},{source:"甬矽电子",target:"全志科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"先进封测→SoC芯片"},{source:"盛科通信",target:"紫光股份",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"以太网交换芯片→H3C交换机，年报点名"},{source:"中芯国际",target:"盛科通信",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"交换芯片代工"},{source:"沪电股份",target:"紫光股份",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"交换机PCB→H3C"},{source:"紫光股份",target:"英伟达",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"AI网络交换机→英伟达GPU集群"},{source:"中钨高新",target:"沪电股份",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"PCB微钻/铣刀→AI服务器PCB，金洲精工全球龙头"},{source:"中钨高新",target:"深南电路",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"PCB钻针→高端PCB制造商"},{source:"中钨高新",target:"鹏鼎控股",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"PCB微钻→FPC龙头"},{source:"中钨高新",target:"胜宏科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"PCB钻针→AI PCB制造商"},{source:"大族数控",target:"沪电股份",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB钻孔/切割设备→AI服务器PCB，年报点名客户"},{source:"大族数控",target:"深南电路",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB设备→IC载板/PCB，年报点名"},{source:"大族数控",target:"胜宏科技",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB设备→AI PCB，年报点名"},{source:"大族数控",target:"东山精密",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB设备→FPC/PCB，年报点名"},
{source:"Soitec",target:"台积电",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"Photonics-SOI晶圆→台积电COUPE硅光平台，全球80%+市占垄断供应，行业格局"},
{source:"Soitec",target:"沪硅产业",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"SOI技术竞争+授权关系，沪硅SOI光电子级验证中"},
{source:"三井金属",target:"深南电路",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"FL/GN级3μm超薄铜箔→mSAP PCB，全球85%+垄断供应，1.6T光模块刚需耗材"},
{source:"三井金属",target:"沪电股份",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"超薄铜箔→AI服务器mSAP PCB，产业报道"},
{source:"三井金属",target:"兴森科技",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"超薄铜箔→PCB/IC载板mSAP工艺"},
{source:"三井金属",target:"中际旭创",type:"L2",method:"L2_news",confidence:0.50,sourceDoc:"铜箔→mSAP PCB→1.6T光模块，多级传递，经PCB厂间接供应"},
// === 国产光刻机链 2026-07-27 ===
{source:"华卓精科",target:"上海微电子",type:"L1",method:"L1_direct",confidence:0.95,sourceDoc:"双工件台核心供应商，全球第二家磁浮工件台，招股书/年报确认供上海微电子"},
{source:"茂莱光学",target:"上海微电子",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"精密光学镜头已进入国产光刻机供应链，招股书/互动易确认"},
{source:"珂玛科技",target:"上海微电子",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"先进陶瓷零部件核心供应商，互动易确认供上海微电子及北方华创/中微/拓荆"},
{source:"珂玛科技",target:"北方华创",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"陶瓷加热器/静电卡盘→刻蚀/PVD设备，互动易确认"},
{source:"珂玛科技",target:"中微公司",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"陶瓷零部件→刻蚀设备，互动易确认"},
{source:"珂玛科技",target:"拓荆科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"陶瓷零部件→CVD设备，互动易确认"},
{source:"上海微电子",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"国产光刻机→晶圆代工龙头，行业公开信息"},
{source:"上海微电子",target:"华虹公司",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"国产光刻机→特色工艺代工"},
{source:"上海微电子",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"国产光刻机→3D NAND制造"},
{source:"芯源微",target:"上海微电子",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"涂胶显影Track与国产光刻机联机量产，行业共识非年报点名"},
// === PCB钻针补充 2026-07-27 ===
{source:"鼎泰高科",target:"沪电股份",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB微钻全球市占26.8%第一，年报确认供沪电AI服务器PCB"},
{source:"鼎泰高科",target:"深南电路",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB微钻→深南电路IC载板/PCB，年报确认"},
{source:"鼎泰高科",target:"鹏鼎控股",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB微钻→鹏鼎FPC，年报确认"},
{source:"鼎泰高科",target:"胜宏科技",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB微钻→胜宏AI PCB，年报确认"},
{source:"鼎泰高科",target:"东山精密",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"PCB微钻→东山精密FPC/PCB，年报确认"},
// === 机器人链 2026-07-28 ===
{source:"绿的谐波",target:"埃斯顿",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"谐波减速器→工业机器人本体，产业链共识"},
{source:"双环传动",target:"埃斯顿",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"RV减速器→工业机器人本体，产业链共识"},
{source:"汇川技术",target:"宁德时代",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"伺服/驱控→锂电设备产线，间接供应"},
{source:"汇川技术",target:"比亚迪",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"伺服/驱控→汽车产线自动化，间接供应"},
{source:"柯力传感",target:"华为",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"六维力传感器→人形机器人，华为送样验证，待搜索恢复补验"},
// === 机器人链 第二批 2026-07-28 ===
{source:"雷赛智能",target:"华为",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"FM2无框电机+空心杯电机+CD伺服驱动器通过华为测试并批量交付，参与华为小脑联合研发"},
{source:"兆威机电",target:"华为",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"灵巧手ZWHAND→华为具身智能战略合作"},
{source:"双林股份",target:"兆威机电",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"行星滚柱丝杠→兆威机电灵巧手送样，零收入验证阶段"},
{source:"双林股份",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"滚珠丝杠送样宇树，零收入验证阶段"},
{source:"双林股份",target:"拓普集团",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"滚珠丝杠送样拓普，零收入验证阶段"},
{source:"兆威机电",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"灵巧手供宇树，微型传动系统适配"},
{source:"兆威机电",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"微型传动系统适配智元机器人"},
// === 机器人链 供应链边 2026-07-28 ===
{source:"汇川技术",target:"埃斯顿",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"伺服/驱控→工业机器人本体，国产龙头供应链直供"},
{source:"奥比中光",target:"宇树科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"独家3D视觉模组供应商份额72%，年报确认，搜索恢复待补验"},
{source:"奥比中光",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"3D视觉适配中，互动易确认"},
{source:"柯力传感",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"送样测试中，互动易确认"},
{source:"雷赛智能",target:"智元机器人",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"获评优秀供应商伙伴，无框电机2025年交付12万台，证券时报/调研纪要"},
// === Tesla Optimus 供应链 2026-07-28 ===
{source:"拓普集团",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"直线/旋转执行器总成，50亿宁波机器人核心部件基地，年产能30万套，年报+公告确认"},
{source:"三花智控",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"机电执行器送样仿生机器人，互动易确认，6.85亿美元马斯克订单"},
{source:"绿的谐波",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"谐波减速器获墨西哥工厂独家供货，人形机器人收入占比约30%，国金证券+高盛调研"},
{source:"鸣志电器",target:"特斯拉",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"空心杯电机全球前三，无刷电机应用于Optimus原型，多家研报交叉验证"},
{source:"柯力传感",target:"特斯拉",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"六维力传感器D样测试/量产验证中，互动易确认"},
// === 三大整机厂供应链 2026-07-28 ===
{source:"绿的谐波",target:"智元机器人",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"谐波减速器独家供应商，已获1万个订单，智元供应商大会确认"},
{source:"中大力德",target:"宇树科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"行星减速器核心供应商，宇树采购量约63%"},
{source:"中大力德",target:"智元机器人",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"获远征A2/灵犀X1量产定点，公司公告"},
{source:"鸣志电器",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"灵巧手空心杯电机独家供应商，订单环比增200%"},
{source:"长盛轴承",target:"宇树科技",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"自润滑轴承+丝杠独家供应商，2025Q1订单增长300%"},
{source:"雷赛智能",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"伺服电机/步进电机供货，研报交叉验证"},
{source:"绿的谐波",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"谐波减速器潜在供应，未确认，待搜索验证"},
{source:"蓝思科技",target:"智元机器人",type:"L1",method:"L1_direct",confidence:0.75,sourceDoc:"批量交付灵犀X1关节模组/DCU控制器/夹爪，智元供应商大会授奖"},
{source:"禾川科技",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"伺服国产第二，供智元远征A2执行器"},
{source:"富临精工",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"与智元成立合资公司，电关节模组"},
{source:"汉威科技",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"子公司能斯达供柔性触觉传感器，互动易确认"},
{source:"博众精工",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"代工整机组装，2024年订单约2000万"},
{source:"五洲新春",target:"特斯拉",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"反向行星滚柱丝杠主力供应商，已入T链量产，36氪/国金证券确认"},
{source:"双环传动",target:"拓普集团",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"RV减速器→拓普执行器总成→特斯拉Optimus，间接二跳供应"},
// === 存储链 2026-07-28 ===
{source:"雅克科技",target:"SK海力士",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"半导体前驱体→DRAM制造，年报确认获海力士批量订单"},
{source:"雅克科技",target:"美光",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"前驱体供应商，年报确认"},
{source:"雅克科技",target:"长江存储",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"前驱体→3D NAND，年报确认"},
{source:"中船特气",target:"SK海力士",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3供应商，年报确认SK海力士为客户"},
{source:"中船特气",target:"美光",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"NF3→DRAM/NAND，年报确认"},
{source:"长江存储",target:"长电科技",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"3D NAND晶圆→先进封测，国内存储产业链"},
{source:"长鑫存储",target:"通富微电",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"DRAM晶圆→封测，国内存储产业链"},
{source:"澜起科技",target:"SK海力士",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"DDR5内存接口芯片→DRAM模组，产业链标准配套"},
{source:"长江存储",target:"江波龙",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"存储模组(eSSD/UFS)→NAND Flash，国产存储产业链"},
{source:"长鑫存储",target:"兆易创新",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"NOR Flash/DRAM→长鑫成熟制程代工，量逐年缩减"},
{source:"中芯国际",target:"兆易创新",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"NOR Flash+MCU主要代工，中芯国际为兆易核心晶圆供应商"},
// === 光刻机链 供应关系 2026-07-28 ===
{source:"茂莱光学",target:"上海微电子",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"光刻机核心光学模块(匀光/投影物镜/棱镜组件)，配合华卓精科等"},
{source:"福晶科技",target:"上海微电子",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"KBBF/LBO晶体→光刻机光源光学元件，国产独供"},
{source:"福晶科技",target:"ASML",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"通过欧洲代理间接供应光学元件"},
{source:"至纯科技",target:"上海微电子",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"高纯工艺+部件清洗，DUV突破后涨停验证光刻机配套关系"},
{source:"波长光电",target:"上海微电子",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"高精度光学元件，离子束抛光，DUV突破后涨停验证潜在供应"},
{source:"江丰电子",target:"上海微电子",type:"L1",method:"L1_direct",confidence:0.90,sourceDoc:"年报确认多层钛合金扩散焊28nm以下光刻机核心冷却部件已量产"},
{source:"海立股份",target:"上海微电子",type:"L1",method:"L1_direct",confidence:0.75,sourceDoc:"封装光刻机冷却系统配套，上海电气体系内关联"},
{source:"新莱应材",target:"上海微电子",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"超高纯管阀/真空腔体，通过ASML/AMAT/LAM认证，国产光刻机真空系统"},
// === AI服务器链 2026-07-28 ===
{source:"浪潮信息",target:"英伟达",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"AI服务器全球领先份额，基于英伟达GPU平台"},
{source:"中科曙光",target:"华为",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"国产服务器龙头，参与DeepSeek液冷系统建设，绑定海光CPU+寒武纪"},
// === AI服务器 被动元件 2026-07-28 ===
{source:"三环集团",target:"英伟达",type:"L2",method:"L2_news",confidence:0.85,sourceDoc:"陶瓷基板+MLCC→英伟达GPU服务器，GB300单机柜44万颗"},
{source:"三环集团",target:"中际旭创",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"光纤陶瓷插芯全球市占70-80%，配套所有NV光模块"},
{source:"三环集团",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"MLCC→AI服务器整机"},
{source:"顺络电子",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"AI电感量产出货，覆盖头部AI服务器客户"},
{source:"风华高科",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"高容/高压MLCC+大电流电感，与国内AI服务器头部企业合作"},
{source:"铂科新材",target:"英伟达",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"芯片电感批量用于AI服务器GPU，2024H1电感收入+139%"},
{source:"铂科新材",target:"工业富联",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"芯片电感→AI服务器代工厂"},
// === AI服务器 光/PCB/网络 2026-07-28 ===
{source:"沪电股份",target:"英伟达",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"AI服务器PCB核心供应商，高速高层板供英伟达GPU服务器"},
{source:"深南电路",target:"华为",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"IC载板+PCB供华为AI服务器/芯片设计厂"},
{source:"高澜股份",target:"浪潮信息",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"浸没液冷模组→AI服务器整机"},
{source:"高澜股份",target:"中科曙光",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"浸没液冷→国产超算/AI服务器"},
{source:"高澜股份",target:"紫光股份",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"浸没液冷模组→新华三AI服务器"},
{source:"蔚蓝锂芯",target:"谷歌",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"BBU备用电芯→Google数据中心，东吴研报确认联合销售入体系"},
{source:"蔚蓝锂芯",target:"亚马逊",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"BBU备用电芯→AWS数据中心，间接供应"},
// === 孤立节点补边 2026-07-28 ===
{source:"宇量晟",target:"中芯国际",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"国产浸没式DUV光刻机→中芯国际验证，2026年交付"},
{source:"宇量晟",target:"华虹公司",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"国产DUV光刻机→华虹半导体，2026年交付"},
{source:"宇量晟",target:"长鑫存储",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"国产DUV光刻机→长鑫存储，2026年交付"},
{source:"国轩高科",target:"大众",type:"L1",method:"L1_equity",confidence:0.90,sourceDoc:"大众战略控股26%，合作开发标准电芯"},
// === 锂电链 国轩上游 2026-07-28 ===
{source:"当升科技",target:"国轩高科",type:"L2",method:"L2_news",confidence:0.75,sourceDoc:"三元正极材料→动力电池，供宁德系及国轩"},
{source:"中伟股份",target:"国轩高科",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"三元前驱体→动力电池，供宁德系及国轩"},
{source:"步科股份",target:"智元机器人",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"无框力矩电机→人形机器人，协作机器人1+N战略延伸"},
{source:"步科股份",target:"宇树科技",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"低压伺服/无框电机→四足/人形机器人"},
{source:"东材科技",target:"南亚新材",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"电子树脂→CCL覆铜板，东材为南亚核心树脂供应商"},
{source:"南亚新材",target:"沪电股份",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CCL→AI服务器PCB，平安证券2025年3月研报确认南亚直接客户含沪电"},
{source:"南亚新材",target:"深南电路",type:"L1",method:"L1_direct",confidence:0.85,sourceDoc:"CCL→IC载板/PCB，平安证券研报确认"},
{source:"南亚新材",target:"胜宏科技",type:"L2",method:"L2_news",confidence:0.80,sourceDoc:"CCL→AI服务器PCB，平安证券研报确认"},
// === 孤立节点补边 2026-07-31 ===
{source:"AXT",target:"源杰科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"砷化镓/磷化铟衬底→光芯片，衬底供应商"},
{source:"AXT",target:"长光华芯",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"砷化镓/磷化铟衬底→光芯片"},
{source:"AXT",target:"仕佳光子",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"磷化铟衬底→光芯片/AWG"},
{source:"驰宏锌锗",target:"长飞光纤",type:"L2",method:"L2_news",confidence:0.60,sourceDoc:"锗→光纤掺杂，锗材料主要供应商"},
{source:"驰宏锌锗",target:"亨通光电",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"锗→光纤掺杂"},
{source:"驰宏锌锗",target:"高德红外",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"锗→红外光学镜头"},
{source:"烽火通信",target:"光迅科技",type:"L1",method:"L1_equity",confidence:0.99,sourceDoc:"同属中国信科集团，光通信设备→光模块/器件"},
{source:"烽火通信",target:"中兴通讯",type:"L2",method:"L2_news",confidence:0.70,sourceDoc:"通信设备同业，光传输/接入/数据通信"},
{source:"中芯国际",target:"汇顶科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"晶圆代工→触控芯片设计，行业共识"},
{source:"台积电",target:"汇顶科技",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"晶圆代工→触控芯片设计"},
{source:"中芯国际",target:"寒武纪",type:"L2",method:"L2_news",confidence:0.65,sourceDoc:"AI训练芯片代工，寒武纪2022入实体清单后转中芯，多源确认中芯7nm代工MLU-590"},
{source:"中芯国际",target:"海光信息",type:"L2",method:"L2_news",confidence:0.55,sourceDoc:"x86 CPU代工，海光2019入实体清单后经中芯南方代工"},
{source:"台积电",target:"龙芯中科",type:"L2",method:"L2_news",confidence:0.40,sourceDoc:"CPU代工【待确认】，3A5000代工归属证据薄，龙芯同列BIS实体清单，确认后再提回"},
{source:"中芯国际",target:"龙芯中科",type:"L1",method:"L1_direct",confidence:0.80,sourceDoc:"CPU成熟制程代工，国产信创链"}
];
// ===== 节点简介映射（S+A级节点） =====
// 格式：{ id: "细分赛道 + 核心能力 + 关键客户/方向" }
const NODE_DESC={
// === S级（8个）===
"中际旭创":"全球光模块龙头，800G/1.6T核心供应商，深度绑定英伟达/谷歌/微软",
"中芯国际":"中国大陆最大晶圆代工厂，成熟制程+先进制程双线布局",
"台积电":"全球晶圆代工绝对霸主，3nm/2nm制程领先，AI芯片核心代工厂",
"三井金属":"FL/GN级3μm超薄铜箔全球垄断85%+，mSAP工艺刚需耗材，已停止标准铜箔供应，供深南/沪电/兴森mSAP产线",
"Soitec":"全球光电子级SOI晶圆垄断者，市占80%+，Smart Cut专利3500+，Photonics-SOI收入破$100M翻倍增长，供台积电COUPE/格罗方德/Tower硅光平台",
"英伟达":"全球AI算力芯片垄断者，GPU+CUDA生态壁垒不可替代",
"华为":"全球通信设备+消费电子巨头，自研麒麟+昇腾AI算力芯片",
"宁德时代":"全球动力电池绝对龙头，市占率37%+，供特斯拉/宝马/蔚来",
"ASML":"全球EUV光刻机独家垄断，先进制程不可绕过的物理瓶颈",
"苹果":"全球消费电子生态霸主，iPhone+可穿戴+服务三位一体",
// === A级 · 光模块/光器件 ===
"新易盛":"光模块一线厂商，800G/1.6T批量出货，供英伟达/Meta/AWS",
"天孚通信":"光引擎/FAU核心供应商，英伟达GTC认证，光器件平台型龙头",
"光迅科技":"光模块+光芯片垂直一体化，供华为基站/数据中心",
// === A级 · 半导体材料 ===
"沪硅产业":"国产大硅片龙头，12英寸导入中芯/华虹/台积电/格罗方德；SOI光电子级验证中，国内唯一接近Soitec的标的",
"天通股份":"国内唯一8英寸光学级铌酸锂晶圆量产，12英寸验证通过，年产能130万片，成本比日本低25%+，供光库/中际旭创",
"南大光电":"电子特气+前驱体双线布局，供中芯/华虹/长存",
"华特气体":"电子特气龙头，高纯氟碳类气体供中芯/华虹/台积电",
"江丰电子":"溅射靶材龙头+光刻机核心冷却部件量产，高纯铝/钛/钽靶材供中芯/台积电",
"安集科技":"CMP抛光液国产唯一，铜/钨/介质抛光液供中芯/华虹",
"有研硅":"12英寸硅片供应商，供中芯/华虹/长存/晶合",
"雅克科技":"半导体前驱体+SOD材料，供海力士/美光/长存",
"立昂微":"硅片+射频芯片双业务，12英寸硅片导入中芯/华虹",
"鼎龙股份":"CMP抛光垫国产唯一突破，供中芯/华虹，打破陶氏垄断",
// === A级 · 半导体设备 ===
"北方华创":"国产半导体设备平台型龙头，刻蚀/薄膜/清洗/CMP全覆盖",
"中微公司":"等离子体刻蚀+MOCVD双龙头，5nm刻蚀进入台积电产线",
"盛美上海":"半导体清洗设备龙头，SAPS/TEBO独家技术，供中芯/华虹/长存",
"拓荆科技":"CVD/PVD薄膜沉积设备龙头，PECVD国内市占率第一",
"华海清科":"CMP设备国内唯一供应商，供中芯/华虹/长存",
// === A级 · 晶圆代工/封测 ===
"华虹公司":"特色工艺晶圆代工龙头，功率器件/BCD/CIS平台",
"甬矽电子":"先进封装新锐，SiP/FC/Bumping全覆盖，供恒玄/韦尔/君正",
"长电科技":"全球第三大封测厂，先进封装全覆盖，供高通/华为/英伟达",
"通富微电":"AMD封测核心供应商，先进封装产能持续扩张",
// === A级 · 芯片设计 ===
"澜起科技":"内存接口芯片全球双寡头，DDR5 RCD/DB市占率40%+",
"韦尔股份":"全球CIS图像传感器第三，手机+汽车双轮驱动",
"海光信息":"国产x86 CPU龙头，DCU兼容CUDA生态，供信创/智算中心",
"寒武纪":"国产AI训练推理芯片龙头，思元系列供智算中心",
// === A级 · PCB/CCL/材料 ===
"沪电股份":"AI服务器PCB龙头，mSAP工艺储备中配1.6T光模块需求，高速高层板供英伟达/华为/中兴",
"深南电路":"PCB+IC载板双龙头，mSAP产能爬坡中供中际旭创1.6T光模块验证，ABF载板填补内资空白，供华为及国内芯片设计厂",
"鹏鼎控股":"全球FPC/PCB出货第一，苹果核心供应商",
"胜宏科技":"AI服务器PCB核心供应商，供英伟达/AMD GPU板卡",
"东山精密":"全球唯一PCB+光芯片+光模块全链条，供苹果/特斯拉/英伟达",
"生益科技":"全球CCL覆铜板前三，高频高速CCL供沪电/深南/鹏鼎/胜宏/东山",
"东材科技":"高速电子树脂龙头，通过生益供英伟达/华为/苹果PCB链",
"菲利华":"半导体石英耗材龙头，供北方华创/中微等设备商，间接服务中芯/华虹/长存",
// === A级 · 被动元件/网络 ===
"铂科新材":"金属磁粉芯龙头，芯片电感进入英伟达供应链，国内主要供应商",
"紫光股份":"企业级网络设备龙头，H3C交换机/路由器供AI数据中心",
"盛科通信":"国产以太网交换芯片龙头，供H3C交换机，对标博通",
// === A级 · 终端/代工/矿产 ===
"比亚迪":"全球新能源车销量冠军，刀片电池+DM-i自研垂直一体化",
"工业富联":"全球最大AI服务器组装厂，英伟达核心代工伙伴",
"立讯精密":"苹果最大组装代工商之一，通信/汽车连接器扩展",
"北方稀土":"全球最大稀土供应商，控制全国60%+稀土开采指标",
"华友钴业":"钴镍冶炼龙头，印尼镍矿+三元前驱体一体化",
"赣锋锂业":"锂业龙头，锂矿+锂盐+电池全产业链",
// === A级 · 海外半导体 ===
"三星电子":"全球存储+逻辑IDM霸主，HBM3E供英伟达",
"SK海力士":"全球HBM存储龙头，HBM3E英伟达核心供应商",
"美光":"全球存储三巨头之一，HBM3E进入英伟达供应链",
"英特尔":"x86 CPU双寡头之一，IDM2.0晶圆代工转型中",
"高通":"全球手机SoC+基带芯片霸主，骁龙供小米/OPPO/vivo",
"博通":"全球通信芯片巨头，DSP/交换芯片供光模块+AI网络",
// === A级 · 海外设备/终端/云厂 ===
"东京电子":"日本半导体设备龙头，涂胶显影/刻蚀全球领先",
"应用材料":"全球最大半导体设备商，沉积/刻蚀/CMP全平台",
"泛林":"全球刻蚀设备双寡头之一，导体刻蚀市占率第一",
"科磊":"全球半导体检测量测设备垄断者",
"特斯拉":"全球电动车先驱，FSD自动驾驶+Optimus人形机器人，A股5家核心供应商",
"谷歌":"北美云厂三巨头之一，TPU自研AI芯片+GCP云",
"微软":"北美云厂三巨头之一，OpenAI核心投资方，Azure AI云",
"亚马逊":"全球云服务市占第一(AWS)，自研Trainium AI芯片",
// === B/C级 · 光模块/光器件/光芯片 ===
"华工科技":"光模块+激光设备双业务，子公司云岭光电自研光芯片，供华为",
"铭普光磁":"光模块+磁性元器件，供华为/中兴",
"博创科技":"PLC光分路器+数通光模块，供华为/中兴",
"腾景科技":"精密光学元件供应商，供中际旭创/天孚通信",
"太辰光":"光纤连接器/陶瓷插芯制造商，供光模块厂商",
"德科立":"光放大器/子系统供应商，供谷歌数据中心",
"剑桥科技":"LPO光模块供应商，经Arista交换机供英伟达GPU集群",
"联特科技":"光模块制造商，供中兴通讯",
"长飞光纤":"全球光纤光缆龙头，预制棒+光纤+光缆+光器件全链",
"亨通光电":"光纤光缆+海洋通信+智能电网",
"烽火通信":"通信设备商，光传输/接入/数据通信，同属中国信科集团",
"源杰科技":"国产光芯片龙头，25G/50G DFB/EML芯片供中际旭创",
"长光华芯":"高功率半导体激光芯片，光通信+VCSEL双线，供国内光模块厂商",
"仕佳光子":"PLC分路器/AWG芯片，供长飞/亨通",
"光库科技":"TFLN薄膜铌酸锂调制器国内唯一量产，市占90%+，1.6T批量出货绑英伟达/谷歌，供中际旭创/新易盛",
// === B/C级 · 半导体设备 ===
"芯源微":"涂胶显影设备国产龙头，供中芯/长鑫",
"华大九天":"国产EDA工具龙头，模拟/数字全流程",
"华峰测控":"半导体测试机供应商",
"长川科技":"半导体测试分选机，供长电/通富",
"芯碁微装":"直写光刻设备，供鹏鼎/深南/胜宏等PCB厂",
// === B/C级 · 半导体材料 ===
"彤程新材":"KrF光刻胶国产化核心供应商，ArF验证中，供国内晶圆厂",
"中船特气":"全球电子特气龙头，NF3/WF6产能世界第一，供台积电/三星/海力士/美光/英特尔/中芯/华虹/长存/长鑫，国内IC特气收入排名第一",
"金宏气体":"电子大宗气体(高纯氨/硅烷)，供半导体厂",
"有研新材":"溅射靶材+稀土材料",
"晶瑞电材":"超纯化学品+光刻胶，供中芯/华虹",
"上海新阳":"电镀液/清洗液，供中芯",
"天岳先进":"SiC衬底龙头，半绝缘型+导电型双线",
"联瑞新材":"硅微粉/球形氧化铝填料，供CCL/EMC封装",
"石英股份":"高纯石英砂，供半导体/光伏坩埚",
// === B/C级 · 晶圆代工/封测 ===
"晶合集成":"DDIC/CIS晶圆代工厂，代工韦尔股份CIS芯片",
"华天科技":"国内封测三强之一，与长电/通富并列",
// === B/C级 · 芯片设计 ===
"格科微":"CIS图像传感器+DDIC，供传音/OPPO/华为/vivo/小米",
"翱捷科技":"蜂窝基带芯片设计，供移远/广和通/中兴",
"龙芯中科":"国产自主CPU龙芯，供浪潮/纳思达，信创核心",
"思瑞浦":"信号链模拟芯片，供华为/中兴基站及服务器",
"圣邦股份":"电源管理+信号链模拟芯片，供华为/小米/海康/中兴",
"兆易创新":"NOR Flash+MCU龙头，NOR/MCU由中芯国际代工，DRAM由长鑫代工(成熟制程，量逐年缩减)，供华为全系",
"卓胜微":"射频前端芯片，供小米/OPPO",
"汇顶科技":"指纹识别/触控芯片，供OPPO/vivo",
"瑞芯微":"AIoT SoC芯片，由格罗方德/中芯代工",
"恒玄科技":"智能音频SoC龙头，供TWS耳机/智能音箱品牌",
"全志科技":"消费级SoC芯片，由台积电代工",
"紫光国微":"特种FPGA+智能安全芯片，信创/军工方向",
"江波龙":"存储模组龙头(eSSD/UFS)，供浪潮AI服务器",
"北京君正":"存储芯片+嵌入式SoC，供小米/OPPO/海康",
"富瀚微":"ISP图像处理芯片，供海康威视",
// === B/C级 · PCB/CCL/材料 ===
"华正新材":"CCL覆铜板供应商，生益科技竞对，供沪电/深南",
"宏和科技":"高端超薄电子布，供生益/华正CCL",
"中国巨石":"全球玻纤龙头市占23%，供生益/华正电子布",
"兴森科技":"IC载板/PCB样板，mSAP工艺能力建设中，供国内IC设计厂",
// === B/C级 · 被动元件/散热 ===
"三环集团":"电子陶瓷龙头，MLCC+陶瓷封装基座，供华为/比亚迪",
"顺络电子":"电感龙头，供小米手机/华为基站",
"风华高科":"老牌被动元件厂，MLCC+电阻，供华为/比亚迪",
"英维克":"数据中心液冷散热龙头，供国内AI数据中心(英伟达GPU平台)",
"高澜股份":"12U浸没液冷模组，供紫光(新华三)/浪潮/中科曙光等国产AI服务器厂商",
"蔚蓝锂芯":"AI服务器BBU备用电芯，进入Google/AWS体系，2026年预计出货5000万颗，东吴买入评级",
"南亚新材":"CCL覆铜板国内老二，M6-M8高速CCL批量供算力客户，适配1.6T/CPO，2025营收52亿+56%，供沪电/深南/胜宏等",
"沃尔核材":"线缆/热缩材料，供华为基站及通信设备",
// === B/C级 · 终端/服务器/通信 ===
"传音控股":"非洲手机之王，新兴市场智能机出货第一",
"浪潮信息":"国内AI服务器龙头，基于英特尔/英伟达平台",
"中科曙光":"国产服务器/超算龙头，绑定海光CPU+寒武纪AI芯片",
"纳思达":"打印机龙头+利盟，国产CPU打印设备",
"移远通信":"全球蜂窝通信模组出货第一",
"广和通":"蜂窝通信模组供应商",
"中兴通讯":"通信设备商，5G基站/承载/核心网全产品线",
"海康威视":"全球安防龙头，AI视觉+机器人新方向",
// === B/C级 · 面板/终端/代工 ===
"京东方":"全球LCD面板出货第一，OLED供苹果/华为旗舰机",
"歌尔股份":"声学/VR/AR组装，苹果Meta核心供应商",
"格力电器":"空调龙头",
"美的集团":"全球家电龙头",
// === B/C级 · 关键矿产/材料 ===
"云南锗业":"锗金属龙头，供光纤掺杂(长飞/亨通)/红外光学",
"洛阳钼业":"全球铜钴矿巨头，CATL入股KFM铜钴矿25%",
"锡业股份":"全球锡业龙头，锡→焊料→PCB间接供应",
"厦门钨业":"钨制品+稀土+锂电正极材料",
"中钨高新":"PCB钻针全球龙头(金洲精工)，供沪电/深南/鹏鼎/胜宏",
"大族数控":"PCB专用设备龙头，年报点名胜宏/深南/沪电/东山为客户",
"铜陵有色":"电解铜龙头，铜→铜箔→CCL原料供应",
"天齐锂业":"全球锂矿巨头，锂精矿/锂盐供宁德时代",
"驰宏锌锗":"锌锗伴生矿，同云南锗业行业并行",
"包钢股份":"包钢集团，控股北方稀土+稀土精矿独家供应",
"中科三环":"钕铁硼永磁龙头，供特斯拉驱动电机",
"金力永磁":"钕铁硼永磁供应商，供比亚迪/特斯拉",
"中国稀土":"六大稀土集团之一",
"嘉元科技":"锂电铜箔龙头，兼供生益CCL",
"诺德股份":"铜箔(锂电+电子电路双线)，供生益/鹏鼎",
"铜冠铜箔":"PCB铜箔龙头，供生益/华正/鹏鼎",
"国瓷材料":"MLCC介质粉体全球主力供应商，供三环/风华/村田",
// === B/C级 · 汽车链/新能源 ===
"拓普集团":"T链机器人执行器Tier1，50亿宁波基地年产能30万套，直线/旋转执行器总成，特斯拉底盘/内饰核心供应商",
"三花智控":"T链机电执行器核心供应商，6.85亿美元马斯克订单，热管理核心供特斯拉",
"旭升集团":"铝合金精密压铸，特斯拉供应商",
"均胜电子":"汽车安全系统/智能座舱，特斯拉供应商",
"德赛西威":"智能座舱/自动驾驶域控，供比亚迪",
"亿纬锂能":"动力电池二线龙头，供小鹏(累计超15万台)",
"国轩高科":"大众战略控股动力电池厂，合作开发标准电芯",
"阳光电源":"光伏逆变器+储能系统全球龙头",
"锦浪科技":"组串式光伏逆变器",
// === B/C级 · 设备零部件/连接器/其他 ===
"富创精密":"半导体设备精密零部件，供北方华创",
"麦格米特":"AI服务器电源方案商",
"鼎通科技":"高速连接器供应商，供AI服务器代工厂",
"赛微电子":"MEMS传感器代工，供谷歌",
"高德红外":"红外探测器/热像仪，军工光电核心",
"兴发集团":"磷化工龙头，电子级磷酸供晶圆制造(多级供应链)",
"多氟多":"电子级氢氟酸龙头，进三星/SK海力士供应链",
"当升科技":"三元正极材料，供宁德时代(长期供应商)",
"容百科技":"高镍正极材料，供宁德时代(核心供应商)",
"中伟股份":"三元前驱体龙头，供宁德时代",
"威迈斯":"车载电源供应商，供比亚迪",
"中航光电":"连接器龙头，供华为基站/服务器/汽车",
"泰和新材":"芳纶纤维，供长飞光缆增强材料",
"格林美":"电池回收龙头，供钴镍原料",
"华峰铝业":"铝材供应商，供宁德时代电池热管理",
// === 海外（无评级）===
"AMD":"x86 CPU+GPU双线，与英伟达/英特尔竞争",
"Meta":"北美云厂，自研AI芯片+开源LLaMA大模型",
"格罗方德":"全球第三大晶圆代工厂(成熟制程为主)",
"联华电子":"全球第四大晶圆代工厂(台系成熟制程)",
"村田":"全球MLCC/被动元件霸主",
"住友电工":"全球磷化铟衬底龙头",
"AXT":"磷化铟/砷化镓衬底供应商，北京通美为全资子公司",
"三菱电机":"光芯片(EML激光器)供应商，供中际旭创",
"Lumentum":"光芯片/激光器，EML供中际旭创",
"Coherent":"光芯片(VCSEL/EML)供应商，供中际旭创",
// === 非上市 ===
"长江存储":"国产3D NAND存储制造，对标三星/SK海力士/美光",
"长鑫存储":"国产DRAM存储制造",
"通美晶体":"AXT全资子公司，磷化铟衬底国产化平台",
"四川飞普":"长飞光纤控股子公司，光器件制造",
"小米":"手机+IoT生态品牌，高通骁龙核心客户",
"OPPO":"手机品牌，高通骁龙客户",
"vivo":"手机品牌，高通骁龙客户",
"小鹏":"电动车品牌，亿纬锂能电池客户(P7+全系搭载)",
"大众":"全球汽车巨头，控股国轩高科26%，合作开发标准电芯",
// === 国产光刻机链 2026-07-27 ===
"上海微电子":"上海微电子，国产光刻机整机龙头，90nm/28nm节点攻坚，供中芯/华虹/长存",
"华卓精科":"全球第二家磁浮双工件台供应商，1.2nm定位精度，独家供SMEE光刻机核心子系统",
"茂莱光学":"精密光学镜头供应商，已进入国产光刻机供应链，供SMEE",
// === 光刻机链 补充 2026-07-28 ===
"福晶科技":"非线性光学晶体全球龙头，光刻机光源光学元件",
"波长光电":"精密光学元件，光刻机照明/投影系统",
"至纯科技":"高纯工艺系统龙头，光刻机配套洁净系统+湿法清洗",
"宇量晟":"上海宇量昇，国产浸没式DUV光刻机已量产，2026年5台交付中芯/华虹/长鑫存储，与中芯国际合作验证中",
"海立股份":"SMEE封装光刻机冷却系统配套，上海电气体系内关联",
"新莱应材":"超高纯管阀/真空腔体，通过ASML/AMAT/LAM认证，国产光刻机真空系统核心供应商",
"张江高科":"持有SMEE上海微电子10.779%股权，光刻机链核心权益标的",
"珂玛科技":"先进陶瓷零部件（静电卡盘/陶瓷加热器），供SMEE/北方华创/中微/拓荆，互动易确认",
"鼎泰高科":"PCB微钻全球市占26.8%第一，供沪电/深南/鹏鼎/胜宏/东山五大PCB厂，年报确认",
"富创精密":"半导体设备精密零部件平台供应商（腔体/气柜/气体管路），供北方华创/中微/拓荆，AMAT/LAM/ASML/TEL国际供应链（海外L2）",
// === A级 · 机器人 2026-07-28 ===
"汇川技术":"国产伺服/驱控绝对龙头，通用伺服市占28%国内第一，SCARA机器人26%，供宁德/比亚迪",
"绿的谐波":"谐波减速器国产龙一，市占26%，定增扩产159万台/年，供埃斯顿/特斯拉(墨西哥工厂独家，人形收入占比~30%)",
"双环传动":"RV减速器国产龙一，市占14%仅次于纳博特斯克，供埃斯顿等机器人本体厂",
// === B/C级 · 机器人 2026-07-28 ===
"柯力传感":"六维力传感器龙头，A股唯一向华为送样并验收的人形机器人传感器厂商，已获协作机器人批量订单",
"埃斯顿":"国产工业机器人出货前三，伺服+机器视觉+本体垂直整合，布局人形关节模组",
"鸣志电器":"伺服+步进电机，3C/医疗协作机器人核心供应商",
// === A级 · 机器人 第二批 2026-07-28 ===
"雷赛智能":"步进系统国内龙头，伺服增速国产第一，FM2电机/空心杯/驱动器通过华为测试批量交付，参与华为小脑联合研发",
"兆威机电":"国内微型传动+灵巧手龙头，ZWHAND二代发布，华为具身智能战略合作",
// === B/C级 · 机器人 第二批 2026-07-28 ===
"双林股份":"行星滚柱丝杠+线性关节模组全自研，向宇树/拓普/兆威送样，零收入送样阶段",
"步科股份":"低压伺服物流市占42%，无框力矩电机2.4万台+69%，已批量供货全球协作机器人龙头(客户名待确认)",
"奥比中光":"3D视觉传感器龙头，营收5.6亿+56%，定增9.8亿机器人AI视觉平台",
"五洲新春":"反向行星滚柱丝杠T链主力供应商，泰国工厂2026年投产，已入T链量产配套",
// === 机器人链 非上市整机 ===
"宇树科技":"国内四足/人形机器人新锐(非上市)，奥比中光独家3D视觉供应商",
"智元机器人":"具身智能机器人创业公司(非上市)，雷赛智能无框电机核心供应商",
// === 机器人链 第三批 2026-07-28 ===
"中大力德":"行星减速器龙头，宇树核心供应商采购量约63%，智元远征A2/灵犀X1量产定点",
"长盛轴承":"宇树自润滑轴承+丝杠独家供应商，2025Q1订单增长300%",
"禾川科技":"伺服国产第二市占4.4%，供智元重载型号远征A2执行器",
"蓝思科技":"智元核心代工+关节模组，批量交付灵犀X1，供应商大会授奖（B/0.75）",
"富临精工":"与智元成立合资公司，电关节模组",
"汉威科技":"触觉传感器，子公司能斯达供宇树柔性触觉传感器",
"博众精工":"智元代工整机组装，2024年订单约2000万",
};